# POST http://localhost:8080/user
# Content-Type: application/json

# {
#     "email":"test@test.com",
#     "password":"dsasa22!",
#     "name":"test"
# }

# POST http://localhost:8080/auth/request
# Content-Type: application/json

# {
#     "phonenumber":"01045099894"
# }

# POST http://localhost:8080/auth/request
# Content-Type: application/json

# {
#     "phonenumber":"01045099894"
# }

# POST http://localhost:8080/auth/check
# Content-Type: application/json

# {
#     "phonenumber":"01045099894",
#     "authnumber":"123456"
# }