version: '3.7'

services:
#   server:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       - TZ:Asia/Seoul
#     ports:
#       - 8080:8080
#     env_file:
#       - ./.development.env
  database:
    platform: linux/arm64
    image: mysql:latest
    volumes:
      - ./src:/usr/app/src
    environment:
      MYSQL_DATABASE: 'server'
      MYSQL_ROOT_PASSWORD: '12Sqecd34!'
      TZ: Asia/Seoul
    ports:
      - 3306:3306
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --requirepass $$REDIS_PASSWORD"
    env_file:
      - .env